name: SURE
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - imageio
  - jinja2
  - matplotlib
  - mindspore==2.4.10
  - monai==1.4.0
  - numpy==1.26.4
  - pillow
  - scikit-image
  - scikit-learn
  - scipy
  - torch==2.5.0
  - torchvision==0.20.0
  - tqdm
